// Generated by tools/sync_pump_create_layout.py; do not edit indices manually.
// Source: https://github.com/pump-fun/pump-public-docs/blob/e0687ae9b7e064a0f54efc7297c65eecfbba3a8f/idl/pump.json
// Quote remaining accounts: @pump-fun/pump-sdk@2.0.0 createV2QuoteRemainingAccounts.
#[allow(dead_code)]
pub(crate) mod create {
    pub const DISCRIMINATOR: [u8; 8] = [24, 30, 200, 40, 5, 28, 7, 119];
    pub const LEN: usize = 14;
    pub const MINT: usize = 0;
    pub const MINT_AUTHORITY: usize = 1;
    pub const BONDING_CURVE: usize = 2;
    pub const ASSOCIATED_BONDING_CURVE: usize = 3;
    pub const GLOBAL: usize = 4;
    pub const MPL_TOKEN_METADATA: usize = 5;
    pub const METADATA: usize = 6;
    pub const USER: usize = 7;
    pub const SYSTEM_PROGRAM: usize = 8;
    pub const TOKEN_PROGRAM: usize = 9;
    pub const ASSOCIATED_TOKEN_PROGRAM: usize = 10;
    pub const RENT: usize = 11;
    pub const EVENT_AUTHORITY: usize = 12;
    pub const PROGRAM: usize = 13;
}
#[allow(dead_code)]
pub(crate) mod create_v2 {
    pub const DISCRIMINATOR: [u8; 8] = [214, 144, 76, 236, 95, 139, 49, 180];
    pub const LEN: usize = 16;
    pub const MINT: usize = 0;
    pub const MINT_AUTHORITY: usize = 1;
    pub const BONDING_CURVE: usize = 2;
    pub const ASSOCIATED_BONDING_CURVE: usize = 3;
    pub const GLOBAL: usize = 4;
    pub const USER: usize = 5;
    pub const SYSTEM_PROGRAM: usize = 6;
    pub const TOKEN_PROGRAM: usize = 7;
    pub const ASSOCIATED_TOKEN_PROGRAM: usize = 8;
    pub const MAYHEM_PROGRAM_ID: usize = 9;
    pub const GLOBAL_PARAMS: usize = 10;
    pub const SOL_VAULT: usize = 11;
    pub const MAYHEM_STATE: usize = 12;
    pub const MAYHEM_TOKEN_VAULT: usize = 13;
    pub const EVENT_AUTHORITY: usize = 14;
    pub const PROGRAM: usize = 15;
}
pub(crate) mod quote_remaining {
    pub const QUOTE_MINT: usize = super::create_v2::LEN + 0;
    pub const QUOTE_VAULT: usize = super::create_v2::LEN + 1;
    pub const QUOTE_TOKEN_PROGRAM: usize = super::create_v2::LEN + 2;
}
