#!/usr/bin/env python3
"""Generate hot-path indices from the reviewed Pump IDL/SDK layout snapshot.

Update tests/fixtures/pump_create_layout.json from the official IDL and SDK,
then run this script. --check detects stale generated code without networking.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
parser.add_argument("--idl", type=Path, help="Refresh fixed account names from an official pump.json")
parser.add_argument("--source", help="Pinned GitHub source URL for the supplied IDL")
args = parser.parse_args()
snapshot = ROOT / "tests/fixtures/pump_create_layout.json"
layout = json.loads(snapshot.read_text())
if args.idl:
    if args.check or not args.source:
        parser.error("--idl requires --source and cannot be combined with --check")
    wire = args.idl.read_bytes()
    idl = json.loads(wire)
    layout["source"] = args.source
    layout["idl_sha256"] = hashlib.sha256(wire).hexdigest()
    layout["instructions"] = [
        {"name": i["name"], "discriminator": i["discriminator"],
         "accounts": [a["name"] for a in i["accounts"]]}
        for i in idl["instructions"] if i["name"] in ("create", "create_v2")
    ]
    if {i["name"] for i in layout["instructions"]} != {"create", "create_v2"}:
        raise SystemExit("IDL must contain both create instructions")
    snapshot.write_text(json.dumps(layout, indent=2) + "\n")
lines = [
    "// Generated by tools/sync_pump_create_layout.py; do not edit indices manually.",
    "// Source: " + layout["source"],
    "// Quote remaining accounts: " + layout["sdk_version"] + " createV2QuoteRemainingAccounts.",
]
for instruction in layout["instructions"]:
    lines.append("#[allow(dead_code)]")
    lines.append("pub(crate) mod " + instruction["name"] + " {")
    discriminator = ", ".join(str(byte) for byte in instruction["discriminator"])
    lines.append(f"    pub const DISCRIMINATOR: [u8; 8] = [{discriminator}];")
    lines.append("    pub const LEN: usize = " + str(len(instruction["accounts"])) + ";")
    for index, name in enumerate(instruction["accounts"]):
        lines.append(f"    pub const {name.upper()}: usize = {index};")
    lines.append("}")
lines.append("pub(crate) mod quote_remaining {")
for index, name in enumerate(layout["sdk_quote_remaining_accounts"][:3]):
    lines.append(f"    pub const {name.upper()}: usize = super::create_v2::LEN + {index};")
lines.append("}")
generated = "\n".join(lines) + "\n"
target = ROOT / "src/instr/pump_create_layout.rs"
if args.check:
    if target.read_text() != generated:
        raise SystemExit("Pump create layout is stale; regenerate it with this script")
else:
    target.write_text(generated)
